---
- name: Install package
  ansible.builtin.include_tasks:
    file: unbound/install.yaml
    apply:
      tags:
        - unbound_install
  tags: unbound_install

- name: Configure required systemd
  ansible.builtin.include_tasks:
    file: systemd/main.yaml
    apply:
      tags:
        - unbound_setup
  tags:
    - unbound_setup

- name: Configure unbound
  ansible.builtin.include_tasks:
    file: unbound/configure.yaml
    apply:
      tags:
        - unbound_update
  tags:
    - unbound_update

# verify output of command in a better way
- name: Verify unbound is working correctly
  ansible.builtin.command: drill {{ unbound_test_domain }}
  changed_when: true
  tags:
    - unbound_update
