---
- name: Install Unbound Package
  ansible.builtin.package:
    name:
      - unbound
      - unbound-anchor
      - dnsutils
      - ldnsutils
      - curl
    state: present
  when: unbound_install
  become: true

- name: Install systemd-resolved on Debian
  ansible.builtin.package:
    name:
      - systemd-resolved
    state: present
  when: unbound_install and ansible_facts['distribution'] == "Debian"
  become: true
