---
- name: Install Unbound Package
  ansible.builtin.package:
    name:
      - unbound
      - unbound-anchor
      - dnsutils
      - ldnsutils
      - curl
    state: present
  when: unbound_install
  become: true
