# terraform managed
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: ubuntu-jammy-jellyfish
    image: "quay.io/pimvh/molecule-ubuntu-jammy-jellyfish:latest"
    tmpfs:
      - /run
      - /tmp
    privileged: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      Ubuntu:
        ansible_user: ansible
verifier:
  name: testinfra
