# terraform managed
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: ubuntu:jammy
    cmd: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: false
    override_command: false
provisioner:
  name: ansible
  instance:
    ansible_user: ansible
verifier:
  name: testinfra