# terraform managed
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: "${IMAGE_NAME}"
    image: "${REGISTRY}/${IMAGE_ID}:latest"
    tmpfs:
      - /run
      - /tmp
    privileged: true
    override_command: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      all:
        ansible_user: ansible
verifier:
  name: testinfra
